### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by FIGHTFORGLO** [oyam/pytorch-DPNs#2]
while I run main.py,the following error occurred:
![tim 20170803173158](https://user-images.githubusercontent.com/30248112/28915446-c02fd2e2-7871-11e7-809f-7d3fea15a0a4.png)
Can you help me?thx.@oyam
I'm sure there are images in the path

**Comment by FIGHTFORGLO** [comment]
I'm sure there are images in the path.

**Comment by oyam** [comment]
I think this error occurs when there are no images in subfolder of data/val. Please check whether there are subfolders and images in it. 

For example:
data/val/dog/xxx.png  
data/val/dog/xxy.png 
data/val/dog/xxz.png   
data/val/cat/123.png
data/val/cat/nsdf3.png
data/val/cat/asd932_.png

For more details, please see https://github.com/pytorch/vision/blob/master/torchvision/datasets/folder.py#L96-L97

**Comment by FIGHTFORGLO** [comment]
Thank you very much,I sovled it.
