### ISSUE TITLE
Question: why "out_chs=num_1x1_c+2*inc" but not "out_chs=num_1x1_c+inc"

### ISSUE THREAD

**Issue by rouniuyizu** [oyam/pytorch-DPNs#3]
https://github.com/oyam/pytorch-DPNs/blob/f5909eddd1b92190e78fb2534815c7c588b264b8/dpn.py#L49

**Comment by oyam** [comment]
Sorry, I don't know why author chose "num_1x1_c + 2 * inc" instead of "num_1x1_c + inc". I set this hyper parameter based on original MXNet implementation. Please refer https://github.com/cypw/DPNs/blob/master/settings/symbol_dpn.py#L30
